# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=LJPINTAC@gmail.com
# Use an App Password if using Gmail with 2FA
spring.mail.password=tofv crwo jlsm cbtw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server port for deployment
server.port=${PORT:8080}
